version: '3.3'

services:

  srv:
#    image: ghcr.io/khorevaa/onec-server
    image: khorevaa/onec-server:8.3.16.1659
    entrypoint: /opt/1C/v8.3/x86_64/ragent
    hostname: srv
    ports:
      - "1540-1541:1540-1541"
      - "1560:1560"
    volumes:
      - srv_data:/home/usr1cv8/.1cv8
      - srv_log:/var/log/1C
    networks:
      - back_net

  db:
    image: rsyuzyov/docker-postgresql-pro-1c
    ports:
      - "${PG_PORT:-5432}:5432"
    volumes:
      - db_data:/var/lib/postgresql
    networks:
      - back_net
  ras:
    image: ghcr.io/khorevaa/onec-server
#    image: khorevaa/onec-server:8.3.16.1659
    entrypoint: /opt/1C/v8.3/x86_64/ras
    command: "cluster srv:1540"
    ports:
      - "${RAS_PORT:-1545}:1545"
    networks:
      - back_net
  ras2:
#    image: ghcr.io/khorevaa/onec-server
    image: khorevaa/onec-server:8.3.16.1659
    entrypoint: /opt/1C/v8.3/x86_64/ras
    command: "cluster srv:1540"
    ports:
      - "${RAS_PORT:-1546}:1545"
    networks:
      - back_net
volumes:
  srv_data: {}
  srv_log: {}
  db_data: {}
  repo_data: {}
  client_data: {}

networks:
  back_net: {}
