on: [push, pull_request]
name: Linter
jobs:
  Golint:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v2
      - name: Granting private modules access
        run: git config --global url."https://${{ secrets.ACCESS_TOKEN }}:x-oauth-basic@github.com/v8".insteadOf "https://github.com/v8"
      - name: Run Golint
        uses: reviewdog/action-golangci-lint@v1
        with:
          golangci_lint_flags: "--tests=false"
